// Build the fixed Material palette using the original, unmodified MCU library.
const fs = require('fs'), path = require('path'), vm = require('vm');
const root = path.resolve(__dirname, '..');
const context = {}; context.window = context; vm.createContext(context);
vm.runInContext(fs.readFileSync(path.join(root,'libs.js'),'utf8'), context);
      var THEME_SOURCE = 0xff5f7285;
      var ROLES = [
        "primary", "onPrimary", "primaryContainer", "onPrimaryContainer",
        "secondary", "onSecondary", "secondaryContainer", "onSecondaryContainer",
        "tertiary", "onTertiary", "tertiaryContainer", "onTertiaryContainer",
        "error", "onError", "errorContainer", "onErrorContainer",
        "background", "onBackground",
        "surface", "onSurface", "surfaceVariant", "onSurfaceVariant",
        "surfaceDim", "surfaceBright", "surfaceContainerLowest", "surfaceContainerLow",
        "surfaceContainer", "surfaceContainerHigh", "surfaceContainerHighest",
        "outline", "outlineVariant", "shadow", "scrim",
        "inverseSurface", "inverseOnSurface", "inversePrimary"
      ];

      function roleToVar(name) {
        return "--md-sys-color-" + name.replace(/[A-Z]/g, function (m) { return "-" + m.toLowerCase(); });
      }

      function argbToHex(argb) {
        var v = (argb & 0xFFFFFF).toString(16);
        while (v.length < 6) { v = "0" + v; }
        return "#" + v;
      }

      function extractRoles(scheme) {
        var out = {};
        ROLES.forEach(function (name) {
          var dc = MCU.MaterialDynamicColors[name];
          if (dc && typeof dc.getArgb === "function") {
            out[roleToVar(name)] = argbToHex(dc.getArgb(scheme));
          }
        });
        return out;
      }

      /* Fixed custom palettes; Material still resolves tonal surfaces and on-colors. */
      function buildThemes(seedArgb) {
        var hct = MCU.Hct.fromInt(seedArgb);
        var palettes = {
          primary: MCU.TonalPalette.fromInt(0xff5f7285),
          secondary: MCU.TonalPalette.fromInt(0xff73777c),
          tertiary: MCU.TonalPalette.fromInt(0xff6b7483),
          neutral: MCU.TonalPalette.fromHueAndChroma(hct.hue, 0),
          neutralVariant: MCU.TonalPalette.fromHueAndChroma(hct.hue, 4),
          error: MCU.TonalPalette.fromHueAndChroma(25, 84)
        };
        function mk(isDark) {
          return new MCU.DynamicScheme({
            sourceColorHct: hct, variant: MCU.Variant.TONAL_SPOT,
            isDark: isDark, contrastLevel: 0,
            primaryPalette: palettes.primary, secondaryPalette: palettes.secondary,
            tertiaryPalette: palettes.tertiary, neutralPalette: palettes.neutral,
            neutralVariantPalette: palettes.neutralVariant, errorPalette: palettes.error
          });
        }
        var scheme = mk(false);
        var lightVars = extractRoles(scheme);
        var referenceVars = {};
        Object.keys(palettes).forEach(function (name) {
          var cssName = name === "neutralVariant" ? "neutral-variant" : name;
          [0, 4, 6, 10, 12, 17, 20, 22, 24, 30, 40, 50, 60, 80, 87, 90, 92, 94, 95, 96, 98, 100].forEach(function (tone) {
            referenceVars["--md-ref-palette-" + cssName + tone] = argbToHex(palettes[name].tone(tone));
          });
        });
        var darkVars = extractRoles(mk(true));
        return { light: lightVars, dark: darkVars, palettes: palettes, reference: referenceVars };
      }


context.seed = THEME_SOURCE;
context.ROLES = ROLES;
context.themeBuilder = '(' + buildThemes.toString() + ')';
context.roleExtractor = '(' + extractRoles.toString() + ')';
context.roleVar = '(' + roleToVar.toString() + ')';
context.hexConverter = '(' + argbToHex.toString() + ')';
vm.runInContext('var roleToVar='+context.roleVar+';var argbToHex='+context.hexConverter+';var extractRoles='+context.roleExtractor+';var buildThemes='+context.themeBuilder+';var themes=buildThemes(seed);',context);
const theme = {seed:context.seed,light:context.themes.light,dark:context.themes.dark,reference:context.themes.reference};
fs.writeFileSync(path.join(root,'theme-tokens.js'),'/* Fixed Material roles; generated by tools/build_theme.cjs. */\nwindow.MineCGSTheme='+JSON.stringify(theme)+';\n');
console.log('Theme tokens:',fs.statSync(path.join(root,'theme-tokens.js')).size,'bytes');
